import React from 'react'
import ReactDOM  from 'react-dom'
// import App from './01-base/01-class组件'
// import App from './01-base/05-事件绑定-1'
// import App from './01-base/07-ref'
// import App from './01-base/08-state'
// import App from './01-base/09-循环渲染'
// import App from './01-base/10-todolist'
// import App from './01-base/12-maizuo'
// import App from './01-base/13-setState同步异步'
// import App from './01-base/14-betterScroll'
// import App from './01-base/16-props'
// import App from './01-base/17-props函数式组件'
// import App from './01-base/19-非受控'
// import App from './01-base/22-受控todolist'
// import App from './02-advanced/01-子传父'
// import App from './02-advanced/02-非受控卖座选项卡功能'
// import App from './02-advanced/06-中间人模式'
// import App from './02-advanced/07-发布订阅'
// import App from './02-advanced/08-发布订阅案例'
// import App from './02-advanced/09-context'
// import App from './02-advanced/12-生命周期-初始化'
// import App from './02-advanced/27-swiper-组件'
import App from './03-hooks/03-useEffect2'


ReactDOM.render(<App />, document.getElementById('root'))